#!/bin/python3
# The main of program include cli interface

import downloader as dl
import video_finder as vf
import play_list_finder as plf
import argparse

# Description for each option and paramer
play_list_des = "If video have play list, find and download all playlist. if play list url given, download all play list. -l will print all the links on stdout\n"
q_des = "144, 360, 480, 720, 1080"
spider_des = "If --spider or -s specify, it will crawl the page given and download all the play list. -l will print all the links on stdout"
just_list_des = "Just print the video's link in stdout"
primary_des = "Any Aparat link such as Playlist Or Normal video"

# Craate Commad line interface
parser = argparse.ArgumentParser(prog="apd", description=primary_des)
parser.add_argument("link", help="Page link")
parser.add_argument("-q", "--quality", help=q_des, default="480", type=int)
# Optional option's
parser.add_argument("-p", "--playlist", help=play_list_des, action="store_true")
parser.add_argument("-l", "--just-list", help=just_list_des, action="store_true")

# Set the variable
args = parser.parse_args()
link = args.link
quality = args.quality
playlist = args.playlist
just_list = args.just_list

videos = [] # list the video url and it's name on a tuple. like this: [("video", "url"), ("video", "url"), etc]
plvideos = [] # list all the page of play list

if(link != None):
    if(playlist == True):
        plvideos = plf.main(link)
        try:
            print("%s video finded" %len(plvideos))
            for i in plvideos:
                videos.append(vf.main(i, quality))
        except:
            print("err")
    else:
        videos.append(vf.main(link, quality))
    if(just_list == True):
        for i in videos:
            print(i[0])
    else:
        pass # downloader shoud call here
else:
    print("Did you miss the link ?")
